# Generated by claude-sonnet-4-6 on 2026-05-01
defmodule MsiyspWeb.ProgressLive do
  use MsiyspWeb, :live_view
  import Ecto.Query
  alias Msiysp.{Repo, Activity}

  @meters_per_mile 1609.34

  @impl true
  def mount(_params, _session, socket) do
    {weeks, total_miles, prior_year_miles} = build_chart_data()

    {:ok,
     assign(socket,
       weeks: weeks,
       total_miles: total_miles,
       prior_year_miles: prior_year_miles
     )}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
    <script>
      window.renderProgressChart = function(el) {
        const weeks = JSON.parse(el.dataset.weeks)
        const labels = weeks.map(w => w.week)
        const values = weeks.map(w => w.miles)
        const orange = "#fc4c02"

        const mainTrace = {
          x: labels,
          y: values,
          type: "scatter",
          mode: "lines+markers",
          fill: "tozeroy",
          line: { color: orange, width: 2 },
          fillcolor: "rgba(252,76,2,0.18)",
          marker: { color: "white", size: 8, line: { color: orange, width: 2 } },
          hoverinfo: "none"
        }

        const hoverTrace = {
          x: labels,
          y: values.map(() => 1),
          type: "bar",
          yaxis: "y2",
          marker: { color: "rgba(0,0,0,0)", line: { width: 0 } },
          hoverinfo: "none",
          showlegend: false
        }

        const layout = {
          margin: { t: 10, r: 20, b: 40, l: 55 },
          xaxis: { type: "date", tickformat: "%b", tickfont: { size: 11, color: "#666" }, showgrid: false, zeroline: false, showline: false },
          yaxis: { showgrid: true, gridcolor: "#ebebeb", ticksuffix: " mi", tickfont: { size: 11, color: "#666" }, rangemode: "tozero", zeroline: false },
          yaxis2: { overlaying: "y", range: [0, 1], showgrid: false, showticklabels: false, zeroline: false },
          bargap: 0,
          plot_bgcolor: "white",
          paper_bgcolor: "white",
          showlegend: false,
          hovermode: "x",
          shapes: []
        }

        const weekLabel = document.getElementById("progress-week-label")
        const distLabel = document.getElementById("progress-distance")
        const timeLabel = document.getElementById("progress-time")
        const elevLabel = document.getElementById("progress-elev")
        const paceLabel = document.getElementById("progress-pace")

        function formatDuration(secs) {
          const h = Math.floor(secs / 3600)
          const m = Math.floor((secs % 3600) / 60)
          return h > 0 ? `${h}h ${m}m` : `${m}m`
        }

        function formatPace(miles, secs) {
          if (!miles || miles === 0) return "—"
          const secsPerMile = secs / miles
          const m = Math.floor(secsPerMile / 60)
          const s = Math.round(secsPerMile % 60).toString().padStart(2, "0")
          return `${m}:${s}/mi`
        }

        function formatElev(meters) {
          const ft = Math.round(meters * 3.28084)
          return ft.toLocaleString("en-US") + " ft"
        }

        function formatDateRange(start, end) {
          const [s_y, s_m, s_d] = start.split("-").map(Number)
          const [e_y, e_m, e_d] = end.split("-").map(Number)
          const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
          if (s_y == e_y) {
            return `${months[s_m-1]} ${s_d} - ${months[e_m-1]} ${e_d}, ${e_y}`
          } else {
            return `${months[s_m-1]} ${s_d}, ${s_y} - ${months[e_m-1]} ${e_d}, ${e_y}`
          }
        }

        const totalMiles = weeks.reduce((s, w) => s + w.miles, 0)
        const totalSecs = weeks.reduce((s, w) => s + w.seconds, 0)
        const totalElevMeters = weeks.reduce((s, w) => s + w.elev_meters, 0)
        const firstWeek = weeks[0]
        const lastWeek = weeks[weeks.length - 1]

        const defaultWeekLabel = formatDateRange(firstWeek.week, lastWeek.week_end)
        const defaultDist = totalMiles.toFixed(2) + " mi"
        const defaultTime = formatDuration(totalSecs)
        const defaultElev = formatElev(totalElevMeters)
        const defaultPace = formatPace(totalMiles, totalSecs)

        function showDefaults() {
          if (weekLabel) weekLabel.textContent = defaultWeekLabel
          if (distLabel) distLabel.textContent = defaultDist
          if (timeLabel) timeLabel.textContent = defaultTime
          if (elevLabel) elevLabel.textContent = defaultElev
          if (paceLabel) paceLabel.textContent = defaultPace
          const header = document.getElementById("progress-header")
          if (header) header.style.visibility = "visible"
        }

        Plotly.react(el, [mainTrace, hoverTrace], layout, { responsive: true, displayModeBar: false })
          .then(() => showDefaults())

        el.on("plotly_hover", function(data) {
          const pt = data.points.find(p => p.pointIndex < weeks.length)
          if (!pt) return
          const idx = pt.pointIndex
          const w = weeks[idx]

          weekLabel.textContent = formatDateRange(w.week, w.week_end)
          distLabel.textContent = w.miles.toFixed(2) + " mi"
          timeLabel.textContent = formatDuration(w.seconds)
          if (elevLabel) elevLabel.textContent = formatElev(w.elev_meters)
          if (paceLabel) paceLabel.textContent = formatPace(w.miles, w.seconds)

          Plotly.relayout(el, {
            shapes: [{ type: "line", x0: w.week, x1: w.week, y0: 0, y1: w.miles, line: { color: "#333", width: 1.5 } }]
          })

          const markerColors = values.map((_, i) => i === idx ? orange : "white")
          const markerSizes  = values.map((_, i) => i === idx ? 10 : 8)
          Plotly.restyle(el, { "marker.color": [markerColors], "marker.size": [markerSizes] }, [0])
        })

        el.on("plotly_unhover", function() {
          showDefaults()
          Plotly.relayout(el, { shapes: [] })
          Plotly.restyle(el, { "marker.color": [values.map(() => "white")], "marker.size": [values.map(() => 8)] }, [0])
        })
      }
    </script>
    <div>
      <h1>Progress</h1>

      <div style="background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <div id="progress-header" style="visibility: hidden;">
          <div style="font-size: 1.1em; font-weight: 700; margin-bottom: 8px;" id="progress-week-label"></div>
          <div style="display: flex; gap: 40px; margin-bottom: 16px;">
            <div>
              <div style="font-size: 0.85em; color: #888;">Distance</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-distance"></div>
            </div>
            <div>
              <div style="font-size: 0.85em; color: #888;">Time</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-time"></div>
            </div>
            <div>
              <div style="font-size: 0.85em; color: #888;">Elev Gain</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-elev"></div>
            </div>
            <div>
              <div style="font-size: 0.85em; color: #888;">Avg Pace</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-pace"></div>
            </div>
          </div>
        </div>
        <div
          id="progress-chart"
          phx-hook="PlotlyChart"
          data-weeks={Jason.encode!(@weeks)}
        >
        </div>
      </div>
    </div>
    """
  end

  defp build_chart_data do
    now = DateTime.utc_now()
    one_year_ago = DateTime.add(now, -365, :day)
    two_years_ago = DateTime.add(now, -730, :day)

    # Fetch two years of runs to compute current + prior year totals
    activities =
      Repo.all(
        from(a in Activity,
          where: a.type == "Run" and a.date >= ^two_years_ago,
          order_by: [asc: a.date],
          select: %{date: a.date, distance_meters: a.distance_meters, duration_seconds: a.duration_seconds, elevation_meters: a.elevation_meters}
        )
      )

    current_year_acts = Enum.filter(activities, &(DateTime.compare(&1.date, one_year_ago) != :lt))
    prior_year_acts = Enum.filter(activities, &(DateTime.compare(&1.date, one_year_ago) == :lt))

    total_miles = sum_miles(current_year_acts)
    prior_year_miles = sum_miles(prior_year_acts)

    # Build weekly buckets for trailing 52 weeks
    weeks = build_weekly_buckets(current_year_acts, one_year_ago, now)

    {weeks, total_miles, prior_year_miles}
  end

  defp sum_miles(acts) do
    acts |> Enum.map(& &1.distance_meters) |> Enum.sum() |> Kernel./(@meters_per_mile)
  end

  defp build_weekly_buckets(activities, start_dt, end_dt) do
    start_date = DateTime.to_date(start_dt)
    end_date = DateTime.to_date(end_dt)
    week_start = Date.add(start_date, -Date.day_of_week(start_date, :monday) + 1)

    by_week =
      Enum.reduce(activities, %{}, fn act, acc ->
        d = DateTime.to_date(act.date)
        wk = Date.add(d, -(Date.day_of_week(d, :monday) - 1))
        miles = act.distance_meters / @meters_per_mile
        secs = act.duration_seconds || 0
        elev = act.elevation_meters || 0
        Map.update(acc, wk, {miles, secs, elev}, fn {m, s, e} -> {m + miles, s + secs, e + elev} end)
      end)

    Stream.iterate(week_start, &Date.add(&1, 7))
    |> Stream.take_while(&(Date.compare(&1, end_date) != :gt))
    |> Enum.map(fn wk ->
      {miles, secs, elev} = Map.get(by_week, wk, {0.0, 0, 0})
      %{
        week: Date.to_string(wk),
        week_end: Date.to_string(Date.add(wk, 6)),
        miles: miles,
        seconds: secs,
        elev_meters: elev
      }
    end)
  end
end
