# Generated by claude-sonnet-4-6 on 2026-05-01
defmodule MsiyspWeb.ProgressLive do
  use MsiyspWeb, :live_view
  import Ecto.Query
  alias Msiysp.{Repo, Activity}

  @meters_per_mile 1609.34

  @impl true
  def mount(_params, _session, socket) do
    {weeks, total_miles, prior_year_miles} = build_chart_data()

    total_seconds = Enum.reduce(weeks, 0, & &1.seconds + &2)
    total_elev_ft = Enum.reduce(weeks, 0.0, & &1.elev_meters + &2) * 3.28084
    total_miles_sum = Enum.reduce(weeks, 0.0, & &1.miles + &2)
    avg_pace = if total_miles_sum > 0, do: total_seconds / total_miles_sum, else: nil

    first_week = List.first(weeks)
    last_week = List.last(weeks)

    {:ok,
     assign(socket,
       weeks: weeks,
       total_miles: total_miles,
       prior_year_miles: prior_year_miles,
       total_seconds: total_seconds,
       total_elev_ft: total_elev_ft,
       avg_pace: avg_pace,
       date_range_start: first_week && first_week.week,
       date_range_end: last_week && last_week.week_end
     )}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div>
      <h1>Progress</h1>

      <div style="background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <div id="progress-header">
          <div style="font-size: 1.1em; font-weight: 700; margin-bottom: 8px;" id="progress-week-label">
            <%= Msiysp.Format.date_range(@date_range_start, @date_range_end) %>
          </div>
          <div style="display: flex; gap: 40px; margin-bottom: 16px;">
            <div>
              <div style="font-size: 0.85em; color: #888;">Distance</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-distance"><%= Float.round(@total_miles, 2) %> mi</div>
            </div>
            <div>
              <div style="font-size: 0.85em; color: #888;">Time</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-time"><%= format_duration(@total_seconds) %></div>
            </div>
            <div>
              <div style="font-size: 0.85em; color: #888;">Elev Gain</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-elev"><%= format_elev(@total_elev_ft) %></div>
            </div>
            <div>
              <div style="font-size: 0.85em; color: #888;">Avg Pace</div>
              <div style="font-size: 1.6em; font-weight: 700;" id="progress-pace"><%= if @avg_pace, do: "#{Msiysp.Format.time(@avg_pace)}/mi", else: "—" %></div>
            </div>
          </div>
        </div>
        <div
          id="progress-chart"
          phx-hook="PlotlyChart"
          data-weeks={Jason.encode!(@weeks)}
        >
        </div>
      </div>
    </div>
    """
  end

  def format_duration(seconds) when seconds < 60, do: "0m"
  def format_duration(seconds) do
    h = div(trunc(seconds), 3600)
    m = div(rem(trunc(seconds), 3600), 60)
    if h > 0, do: "#{h}h #{m}m", else: "#{m}m"
  end

  def format_elev(ft) do
    n = round(ft)
    formatted = n |> Integer.to_string() |> String.reverse() |> String.replace(~r/(\d{3})(?=\d)/, "\\1,") |> String.reverse()
    "#{formatted} ft"
  end

  defp build_chart_data do
    now = DateTime.utc_now()
    one_year_ago = DateTime.add(now, -365, :day)
    two_years_ago = DateTime.add(now, -730, :day)

    # Fetch two years of runs to compute current + prior year totals
    activities =
      Repo.all(
        from(a in Activity,
          where: a.type == "Run" and a.date >= ^two_years_ago,
          order_by: [asc: a.date],
          select: %{date: a.date, distance_meters: a.distance_meters, duration_seconds: a.duration_seconds, elevation_meters: a.elevation_meters}
        )
      )

    current_year_acts = Enum.filter(activities, &(DateTime.compare(&1.date, one_year_ago) != :lt))
    prior_year_acts = Enum.filter(activities, &(DateTime.compare(&1.date, one_year_ago) == :lt))

    total_miles = sum_miles(current_year_acts)
    prior_year_miles = sum_miles(prior_year_acts)

    # Build weekly buckets for trailing 52 weeks
    weeks = build_weekly_buckets(current_year_acts, one_year_ago, now)

    {weeks, total_miles, prior_year_miles}
  end

  defp sum_miles(acts) do
    acts |> Enum.map(& &1.distance_meters) |> Enum.sum() |> Kernel./(@meters_per_mile)
  end

  defp build_weekly_buckets(activities, start_dt, end_dt) do
    start_date = DateTime.to_date(start_dt)
    end_date = DateTime.to_date(end_dt)
    week_start = Date.add(start_date, -Date.day_of_week(start_date, :monday) + 1)

    by_week =
      Enum.reduce(activities, %{}, fn act, acc ->
        d = DateTime.to_date(act.date)
        wk = Date.add(d, -(Date.day_of_week(d, :monday) - 1))
        miles = act.distance_meters / @meters_per_mile
        secs = act.duration_seconds || 0
        elev = act.elevation_meters || 0
        Map.update(acc, wk, {miles, secs, elev}, fn {m, s, e} -> {m + miles, s + secs, e + elev} end)
      end)

    Stream.iterate(week_start, &Date.add(&1, 7))
    |> Stream.take_while(&(Date.compare(&1, end_date) != :gt))
    |> Enum.map(fn wk ->
      {miles, secs, elev} = Map.get(by_week, wk, {0.0, 0, 0})
      %{
        week: Date.to_string(wk),
        week_end: Date.to_string(Date.add(wk, 6)),
        miles: miles,
        seconds: secs,
        elev_meters: elev
      }
    end)
  end
end
